### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Yerimah** [omarsalem7/Catalog-of-things#29]
[Prioject Kanban board](https://github.com/omarsalem7/Catalog-of-things/projects/1)

We are a group of three working on this project

omarsalem7 was assigned the tasks of `Team member #1`
Yerimah was assigned the tasks of `Team member #2`
BertrandConxy was assigned the tasks of `Team member #3`

**Comment by Meltrust** [comment]
Hi @Yerimah,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Nice task distribution✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

## According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/165058294-96d34457-38d1-4a4d-ac72-f27909a3261e.png)

A description was not provided for several cards:

![image](https://user-images.githubusercontent.com/57421823/165058854-08dea5d1-e995-433f-8459-ed8cf79dcbee.png)


Therefore:

- [ ] Please, add a proper description to those tasks that don't have any.  That way, we will meet this particular requirement 💪 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yerimah** [comment]
Description has been added on all the project cards.

**Comment by dasileker** [comment]
### **Hi @omarsalem7,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
